INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17d0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 0.002(s), this was the 1st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17ef50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 1.004(s), this was the 2nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 3rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16ccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 2.006(s), this was the 3rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 4th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17ffd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 3.010(s), this was the 4th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 5th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17dad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 4.011(s), this was the 5th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 6th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa337250>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 5.013(s), this was the 6th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 7th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16ea50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 6.015(s), this was the 7th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 8th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa160810>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 7.018(s), this was the 8th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 9th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa162550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 8.020(s), this was the 9th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 10th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa161b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 9.023(s), this was the 10th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 11th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa161110>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 10.025(s), this was the 11th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 12th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa337c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 11.027(s), this was the 12th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 13th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16f0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 12.029(s), this was the 13th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 14th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16cb50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 13.031(s), this was the 14th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 15th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17d890>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 14.034(s), this was the 15th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 16th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa32ac90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 15.036(s), this was the 16th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 17th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17f210>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 16.039(s), this was the 17th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 18th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16e0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 17.041(s), this was the 18th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 19th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16fb10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 18.045(s), this was the 19th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 20th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16c710>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 19.047(s), this was the 20th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 21st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa1622d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 20.049(s), this was the 21st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 22nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffaeb8a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 21.053(s), this was the 22nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 23rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa161450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 22.055(s), this was the 23rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 24th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa1633d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 23.057(s), this was the 24th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 25th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16cdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 24.059(s), this was the 25th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 26th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16e690>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 25.061(s), this was the 26th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 27th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17c350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 26.064(s), this was the 27th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 28th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa158510>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 27.067(s), this was the 28th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 29th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16fb10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 28.069(s), this was the 29th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 30th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16f150>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 29.072(s), this was the 30th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 31st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17d350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 30.073(s), this was the 31st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 32nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa160050>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 31.075(s), this was the 32nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 33rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa161a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 32.077(s), this was the 33rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 34th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa158410>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 33.079(s), this was the 34th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 35th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa1610d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 34.082(s), this was the 35th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 36th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa163fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 35.084(s), this was the 36th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 37th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16d350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 36.087(s), this was the 37th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 38th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16d050>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 37.089(s), this was the 38th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 39th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17d4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 38.090(s), this was the 39th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 40th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa158790>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 39.093(s), this was the 40th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 41st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17fe90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 40.095(s), this was the 41st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 42nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16eb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 41.097(s), this was the 42nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 43rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16d090>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 42.099(s), this was the 43rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 44th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa337b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 43.102(s), this was the 44th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 45th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa162350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 44.104(s), this was the 45th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 46th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa158550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 45.107(s), this was the 46th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 47th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa160210>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 46.109(s), this was the 47th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 48th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa162050>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 47.111(s), this was the 48th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 49th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16fa10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 48.113(s), this was the 49th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 50th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16e450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 49.115(s), this was the 50th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 51st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17d690>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 50.117(s), this was the 51st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 52nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa158650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 51.119(s), this was the 52nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 53rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16cd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 52.122(s), this was the 53rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 54th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16fb50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 53.123(s), this was the 54th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 55th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17e810>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 54.125(s), this was the 55th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 56th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa1605d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 55.127(s), this was the 56th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 57th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa162150>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 56.129(s), this was the 57th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 58th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa158450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 57.132(s), this was the 58th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 59th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa161c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 58.134(s), this was the 59th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 60th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa161f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 59.137(s), this was the 60th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 61st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17e810>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 60.139(s), this was the 61st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 62nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16e190>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 61.141(s), this was the 62nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 63rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 62.143(s), this was the 63rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 64th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa158190>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 63.145(s), this was the 64th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 65th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa16e290>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 64.149(s), this was the 65th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 66th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa6fe1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 65.151(s), this was the 66th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 67th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa17d110>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 66.153(s), this was the 67th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 68th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa337710>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 67.155(s), this was the 68th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 69th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4ffa161190>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 68.158(s), this was the 69th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 70th time calling it.
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e0c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 0.002(s), this was the 1st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 1.004(s), this was the 2nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 3rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8850>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 2.007(s), this was the 3rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 4th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 3.010(s), this was the 4th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 5th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 4.013(s), this was the 5th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 6th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a2b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 5.016(s), this was the 6th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 7th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 6.018(s), this was the 7th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 8th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 7.020(s), this was the 8th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 9th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ce110>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 8.022(s), this was the 9th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 10th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a2ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 9.025(s), this was the 10th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 11th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232dbc90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 10.027(s), this was the 11th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 12th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8910>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 11.029(s), this was the 12th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 13th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655238a5390>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 12.031(s), this was the 13th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 14th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 13.035(s), this was the 14th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 15th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ce3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 14.040(s), this was the 15th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 16th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e29d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 15.044(s), this was the 16th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 17th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3190>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 16.047(s), this was the 17th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 18th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 17.049(s), this was the 18th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 19th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d93d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 18.051(s), this was the 19th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 20th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232db950>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 19.053(s), this was the 20th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 21st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cda10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 20.056(s), this was the 21st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 22nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765524524610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 21.060(s), this was the 22nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 23rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e0150>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 22.062(s), this was the 23rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 24th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2390>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 23.064(s), this was the 24th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 25th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 24.066(s), this was the 25th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 26th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9250>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 25.068(s), this was the 26th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 27th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc250>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 26.071(s), this was the 27th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 28th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d4090>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 27.073(s), this was the 28th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 29th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 28.076(s), this was the 29th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 30th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 29.078(s), this was the 30th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 31st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9910>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 30.081(s), this was the 31st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 32nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232db710>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 31.084(s), this was the 32nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 33rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cdd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 32.086(s), this was the 33rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 34th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a2550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 33.090(s), this was the 34th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 35th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 34.092(s), this was the 35th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 36th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 35.095(s), this was the 36th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 37th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 36.097(s), this was the 37th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 38th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 37.100(s), this was the 38th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 39th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3410>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 38.102(s), this was the 39th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 40th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765523ec2c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 39.105(s), this was the 40th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 41st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1810>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 40.108(s), this was the 41st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 42nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cee10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 41.110(s), this was the 42nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 43rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc190>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 42.113(s), this was the 43rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 44th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 43.116(s), this was the 44th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 45th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232db710>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 44.118(s), this was the 45th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 46th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76552343cb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 45.122(s), this was the 46th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 47th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 46.124(s), this was the 47th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 48th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 47.127(s), this was the 48th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 49th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd790>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 48.129(s), this was the 49th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 50th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cdc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 49.132(s), this was the 50th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 51st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 50.135(s), this was the 51st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 52nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 51.138(s), this was the 52nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 53rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ce910>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 52.141(s), this was the 53rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 54th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cdfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 53.144(s), this was the 54th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 55th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 54.146(s), this was the 55th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 56th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 55.148(s), this was the 56th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 57th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 56.150(s), this was the 57th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 58th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a3210>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 57.152(s), this was the 58th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 59th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8190>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 58.154(s), this was the 59th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 60th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d96d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 59.157(s), this was the 60th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 61st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd050>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 60.159(s), this was the 61st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 62nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ce850>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 61.162(s), this was the 62nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 63rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3850>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 62.164(s), this was the 63rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 64th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765523886210>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 63.166(s), this was the 64th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 65th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cf090>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 64.169(s), this was the 65th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 66th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ce690>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 65.171(s), this was the 66th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 67th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3810>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 66.173(s), this was the 67th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 68th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da110>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 67.175(s), this was the 68th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 69th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 68.177(s), this was the 69th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 70th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76552343cb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 69.179(s), this was the 70th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 71st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8910>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 70.181(s), this was the 71st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 72nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232dbd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 71.185(s), this was the 72nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 73rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc590>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 72.187(s), this was the 73rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 74th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cccd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 73.189(s), this was the 74th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 75th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2950>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 74.191(s), this was the 75th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 76th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765523496c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 75.193(s), this was the 76th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 77th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd890>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 76.195(s), this was the 77th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 78th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ce4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 77.198(s), this was the 78th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 79th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 78.200(s), this was the 79th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 80th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232daed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 79.202(s), this was the 80th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 81st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da850>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 80.205(s), this was the 81st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 82nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a3250>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 81.207(s), this was the 82nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 83rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8ad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 82.209(s), this was the 83rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 84th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232daad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 83.212(s), this was the 84th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 85th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3210>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 84.214(s), this was the 85th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 86th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 85.217(s), this was the 86th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 87th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 86.220(s), this was the 87th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 88th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765523496bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 87.223(s), this was the 88th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 89th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cfd50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 88.224(s), this was the 89th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 90th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 89.226(s), this was the 90th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 91st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2a50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 90.229(s), this was the 91st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 92nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da490>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 91.231(s), this was the 92nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 93rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8310>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 92.233(s), this was the 93rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 94th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a2f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 93.235(s), this was the 94th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 95th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e26d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 94.239(s), this was the 95th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 96th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2310>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 95.241(s), this was the 96th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 97th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9710>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 96.243(s), this was the 97th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 98th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765524059c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 97.245(s), this was the 98th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 99th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 98.247(s), this was the 99th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 100th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cead0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 99.250(s), this was the 100th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 101st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ce650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 100.252(s), this was the 101st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 102nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cde90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 101.254(s), this was the 102nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 103rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 102.255(s), this was the 103rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 104th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a3c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 103.257(s), this was the 104th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 105th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 104.258(s), this was the 105th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 106th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 105.261(s), this was the 106th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 107th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3110>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 106.265(s), this was the 107th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 108th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 107.270(s), this was the 108th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 109th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232dadd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 108.272(s), this was the 109th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 110th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765523496990>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 109.275(s), this was the 110th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 111st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 110.277(s), this was the 111st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 112nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765524555790>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 111.280(s), this was the 112nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 113rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232db7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 112.282(s), this was the 113rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 114th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da210>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 113.284(s), this was the 114th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 115th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9210>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 114.289(s), this was the 115th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 116th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd3d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 115.293(s), this was the 116th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 117th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3790>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 116.294(s), this was the 117th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 118th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e05d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 117.298(s), this was the 118th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 119th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e28d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 118.301(s), this was the 119th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 120th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 119.303(s), this was the 120th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 121st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 120.305(s), this was the 121st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 122nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765523496e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 121.308(s), this was the 122nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 123rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cce50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 122.310(s), this was the 123rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 124th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76552343cb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 123.314(s), this was the 124th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 125th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9890>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 124.317(s), this was the 125th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 126th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232dab10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 125.320(s), this was the 126th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 127th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 126.322(s), this was the 127th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 128th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 127.325(s), this was the 128th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 129th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2410>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 128.328(s), this was the 129th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 130th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a2510>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 129.330(s), this was the 130th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 131st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1d90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 130.332(s), this was the 131st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 132nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9850>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 131.334(s), this was the 132nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 133rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232db150>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 132.337(s), this was the 133rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 134th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cdad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 133.339(s), this was the 134th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 135th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 134.341(s), this was the 135th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 136th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234967d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 135.344(s), this was the 136th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 137th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9a10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 136.346(s), this was the 137th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 138th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 137.348(s), this was the 138th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 139th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cf950>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 138.351(s), this was the 139th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 140th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cf390>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 139.353(s), this was the 140th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 141st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2e50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 140.355(s), this was the 141st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 142nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a3c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 141.358(s), this was the 142nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 143rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 142.360(s), this was the 143rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 144th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cf550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 143.363(s), this was the 144th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 145th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 144.365(s), this was the 145th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 146th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 145.367(s), this was the 146th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 147th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da250>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 146.370(s), this was the 147th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 148th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655238a5390>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 147.372(s), this was the 148th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 149th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9c50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 148.375(s), this was the 149th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 150th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8890>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 149.376(s), this was the 150th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 151st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cfc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 150.380(s), this was the 151st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 152nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cfdd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 151.383(s), this was the 152nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 153rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 152.385(s), this was the 153rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 154th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a3e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 153.387(s), this was the 154th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 155th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cf9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 154.389(s), this was the 155th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 156th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ccbd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 155.391(s), this was the 156th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 157th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2910>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 156.394(s), this was the 157th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 158th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232da050>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 157.396(s), this was the 158th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 159th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8790>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 158.398(s), this was the 159th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 160th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76552343e610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 159.400(s), this was the 160th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 161st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 160.402(s), this was the 161st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 162nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d8e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 161.404(s), this was the 162nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 163rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1990>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 162.406(s), this was the 163rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 164th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765524524610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 163.408(s), this was the 164th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 165th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cc650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 164.410(s), this was the 165th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 166th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cce90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 165.412(s), this was the 166th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 167th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd890>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 166.415(s), this was the 167th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 168th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655234a3090>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 167.417(s), this was the 168th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 169th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 168.420(s), this was the 169th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 170th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x76552343dc50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 169.422(s), this was the 170th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 171st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9090>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 170.424(s), this was the 171st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 172nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232db4d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 171.428(s), this was the 172nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 173rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e0ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 172.430(s), this was the 173rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 174th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e2090>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 173.432(s), this was the 174th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 175th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765523496c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 174.434(s), this was the 175th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 176th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232db090>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 175.437(s), this was the 176th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 177th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cf610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 176.440(s), this was the 177th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 178th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232ce610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 177.443(s), this was the 178th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 179th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cce10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 178.445(s), this was the 179th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 180th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232cd390>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 179.447(s), this was the 180th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 181st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 180.450(s), this was the 181st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 182nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e1450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 181.451(s), this was the 182nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 183rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232d9d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 182.453(s), this was the 183rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 184th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x765523694490>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 183.456(s), this was the 184th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 185th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7655232e3290>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 184.458(s), this was the 185th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 186th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7655232e34d0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 185.467(s), this was the 186th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 187th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7655232d8650>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 186.478(s), this was the 187th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 188th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7655232dbad0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 187.487(s), this was the 188th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 189th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7655232cc390>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 188.494(s), this was the 189th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 190th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x765523496bd0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 189.502(s), this was the 190th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 191st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7655232ccb50>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 190.511(s), this was the 191st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 192nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7655232cd4d0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 191.521(s), this was the 192nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 193rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7655232e2710>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 192.529(s), this was the 193rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 194th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7655232e0c90>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 193.537(s), this was the 194th time calling it.
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d945939c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 0.003(s), this was the 1st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c2e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 1.006(s), this was the 2nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 3rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b8b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 2.008(s), this was the 3rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 4th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c3f10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 3.010(s), this was the 4th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 5th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c1910>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 4.012(s), this was the 5th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 6th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9455838d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 5.015(s), this was the 6th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 7th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ba950>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 6.017(s), this was the 7th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 8th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ac710>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 7.019(s), this was the 8th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 9th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ae450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 8.022(s), this was the 9th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 10th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d946455f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 9.025(s), this was the 10th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 11th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453bbf90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 10.027(s), this was the 11th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 12th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ba8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 11.029(s), this was the 12th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 13th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c13d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 12.032(s), this was the 13th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 14th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c1b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 13.034(s), this was the 14th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 15th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ae350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 14.037(s), this was the 15th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 16th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c3f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 15.039(s), this was the 16th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 17th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c1fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 16.041(s), this was the 17th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 18th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c2250>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 17.043(s), this was the 18th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 19th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b9e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 18.047(s), this was the 19th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 20th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453bb5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 19.050(s), this was the 20th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 21st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453afb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 20.052(s), this was the 21st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 22nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d946407450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 21.057(s), this was the 22nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 23rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b8c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 22.060(s), this was the 23rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 24th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ba9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 23.062(s), this was the 24th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 25th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b91d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 24.064(s), this was the 25th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 26th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c2c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 25.067(s), this was the 26th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 27th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ad610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 26.071(s), this was the 27th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 28th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453a4450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 27.073(s), this was the 28th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 29th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c3110>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 28.076(s), this was the 29th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 30th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c07d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 29.078(s), this was the 30th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 31st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b8f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 30.081(s), this was the 31st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 32nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453bb390>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 31.083(s), this was the 32nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 33rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ad390>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 32.085(s), this was the 33rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 34th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453a4350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 33.088(s), this was the 34th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 35th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453baf10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 34.091(s), this was the 35th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 36th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b9850>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 35.094(s), this was the 36th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 37th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ba350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 36.096(s), this was the 37th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 38th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453afbd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 37.098(s), this was the 38th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 39th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c2f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 38.100(s), this was the 39th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 40th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9454b6890>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 39.102(s), this was the 40th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 41st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c1ed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 40.103(s), this was the 41st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 42nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ae450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 41.105(s), this was the 42nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 43rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ac650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 42.107(s), this was the 43rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 44th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b9fd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 43.110(s), this was the 44th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 45th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453bb7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 44.112(s), this was the 45th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 46th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453a4610>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 45.115(s), this was the 46th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 47th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ba010>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 46.117(s), this was the 47th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 48th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b9810>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 47.120(s), this was the 48th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 49th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453adb90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 48.122(s), this was the 49th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 50th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ae690>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 49.124(s), this was the 50th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 51st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c2550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 50.125(s), this was the 51st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 52nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c0290>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 51.128(s), this was the 52nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 53rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453aeed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 52.130(s), this was the 53rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 54th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453adf90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 53.132(s), this was the 54th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 55th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c2550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 54.134(s), this was the 55th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 56th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d945576b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 55.135(s), this was the 56th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 57th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b8f50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 56.137(s), this was the 57th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 58th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453a4050>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 57.139(s), this was the 58th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 59th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453bb410>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 58.141(s), this was the 59th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 60th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453b9950>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 59.143(s), this was the 60th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 61st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ac8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 60.145(s), this was the 61st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 62nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453afc90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 61.147(s), this was the 62nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 63rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c1990>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 62.150(s), this was the 63rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 64th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d946155b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 63.152(s), this was the 64th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 65th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ac050>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 64.154(s), this was the 65th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 66th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453ad350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 65.155(s), this was the 66th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 67th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70d9453c1850>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 66.157(s), this was the 67th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 68th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453bb390>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 67.167(s), this was the 68th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 69th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453b8f10>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 68.175(s), this was the 69th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 70th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453a4310>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 69.185(s), this was the 70th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 71st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453b8fd0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 70.193(s), this was the 71st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 72nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453bb2d0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 71.201(s), this was the 72nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 73rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453ac3d0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 72.209(s), this was the 73rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 74th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453af8d0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 73.217(s), this was the 74th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 75th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453c2510>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 74.225(s), this was the 75th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 76th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x70d9453a4450>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 75.233(s), this was the 76th time calling it.
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c048321d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 0.003(s), this was the 1st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c6c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 1.006(s), this was the 2nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 3rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bc990>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 2.008(s), this was the 3rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 4th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c7e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 3.010(s), this was the 4th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 5th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c5f90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 4.013(s), this was the 5th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 6th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c03b87350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 5.015(s), this was the 6th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 7th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039be750>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 6.016(s), this was the 7th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 8th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039b0510>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 7.019(s), this was the 8th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 9th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039b2250>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 8.021(s), this was the 9th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 10th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c03b86d10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 9.025(s), this was the 10th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 11th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bfed0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 10.029(s), this was the 11th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 12th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bea90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 11.031(s), this was the 12th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 13th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c5450>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 12.033(s), this was the 13th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 14th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c7110>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 13.035(s), this was the 14th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 15th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039b25d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 14.037(s), this was the 15th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 16th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c7b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 15.039(s), this was the 16th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 17th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c6d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 16.041(s), this was the 17th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 18th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c7350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 17.043(s), this was the 18th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 19th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bf150>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 18.045(s), this was the 19th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 20th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bf650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 19.055(s), this was the 20th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 21st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039b1650>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 20.058(s), this was the 21st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 22nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c046fe150>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 21.064(s), this was the 22nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 23rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c7550>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 22.066(s), this was the 23rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 24th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c6b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 23.068(s), this was the 24th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 25th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bee50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 24.070(s), this was the 25th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 26th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bdb50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 25.073(s), this was the 26th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 27th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039b22d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 26.074(s), this was the 27th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 28th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039ac190>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 27.077(s), this was the 28th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 29th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039beb10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 28.079(s), this was the 29th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 30th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bfe50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 29.082(s), this was the 30th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 31st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c54d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 30.084(s), this was the 31st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 32nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c4e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 31.088(s), this was the 32nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 33rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039b24d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 32.092(s), this was the 33rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 34th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039ac150>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 33.094(s), this was the 34th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 35th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c7190>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 34.099(s), this was the 35th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 36th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039c6b10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 35.102(s), this was the 36th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 37th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039b2d50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 36.104(s), this was the 37th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 38th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bd5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 37.107(s), this was the 38th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 39th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c039bd990>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 38.112(s), this was the 39th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 40th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7c5c04bff910>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 39.115(s), this was the 40th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 41st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c039bf910>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 40.124(s), this was the 41st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 42nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c03b7a950>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 41.132(s), this was the 42nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 43rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c039b3110>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 42.140(s), this was the 43rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 44th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c039c6e10>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 43.148(s), this was the 44th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 45th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c039c4e50>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 44.155(s), this was the 45th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 46th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c03abab50>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 45.166(s), this was the 46th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 47th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c039c7450>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 46.177(s), this was the 47th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 48th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c03b7a9d0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 47.184(s), this was the 48th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 49th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c039b28d0>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 48.191(s), this was the 49th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 50th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7c5c039b3590>: Failed to resolve 'src-backend-1' ([Errno -5] No address associated with hostname)"))
WARNING:__main__:Finished call to '__main__.init' after 49.199(s), this was the 50th time calling it.
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4da9f0a1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 0.002(s), this was the 1st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4da909ec10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 1.004(s), this was the 2nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 3rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4da9094990>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 2.007(s), this was the 3rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 4th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4da909fe10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 3.009(s), this was the 4th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 5th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4da909df90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 4.011(s), this was the 5th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 6th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4da925f350>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 5.013(s), this was the 6th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 7th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7a4da9096750>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 6.015(s), this was the 7th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 8th time calling it.
INFO:__main__:Service finished initializing
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x743a59addd90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 0.002(s), this was the 1st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x743a59566b90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 1.005(s), this was the 2nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 3rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x743a5955c910>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 2.007(s), this was the 3rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 4th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x743a59567b50>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 3.010(s), this was the 4th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 5th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x743a59566790>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 4.012(s), this was the 5th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 6th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x743a59726750>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 5.014(s), this was the 6th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 7th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x743a5955e690>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 6.016(s), this was the 7th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 8th time calling it.
INFO:__main__:Service finished initializing
INFO:__main__:Initializing service
INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f053ee65290>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 0.002(s), this was the 1st time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 2nd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f053ee67110>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 1.004(s), this was the 2nd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 3rd time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f053ee54e10>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 2.006(s), this was the 3rd time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 4th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f053ee67e90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 3.009(s), this was the 4th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 5th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f053ee65a90>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 4.012(s), this was the 5th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 6th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f053f01f490>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 5.015(s), this was the 6th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 7th time calling it.
ERROR:__main__:HTTPConnectionPool(host='src-backend-1', port=80): Max retries exceeded with url: /api/api_v1/modifier/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f053ee56bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
WARNING:__main__:Finished call to '__main__.init' after 6.017(s), this was the 7th time calling it.
INFO:__main__:Starting call to '__main__.init', this is the 8th time calling it.
INFO:__main__:Service finished initializing
